#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  6 18:24:41 2018

@author: haswani
"""

import numpy as np
import cv2

img = cv2.imread('watch.jpg', cv2.IMREAD_COLOR) 
#immediately converting to gray


#changing pixel

img[55, 55] = [255,255,255]
px = img[55 ,55]

print(px)


#ROI= region of image

roi = img[100:150, 100:150]

#convert this region

img[10:150 ,100:150] = [255,255,255]

#moving ROI

watch_face = img[37:111, 107:194]

#re-defing a region

img[0:74, 0:87] = watch_face #as to be same size

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
