#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 29 14:20:33 2018

@author: haswani
"""
import numpy as np
from skimage.morphology import skeletonize,skeletonize_3d

x,y,z = np.mgrid[-10:10:0.1, -10:10:0.1, -10:10:0.1]
fil = np.array(x**2 + y**2 < 3).astype(np.uint8)
print(fil)
dskel = skeletonize_3d(fil)
print(dskel)
